console:
    path:  /
    defaults: { _controller: CoreSphereConsoleBundle:Console:console }
    requirements:
        _method: GET


console_exec:
    path:  /commands.{_format}
    defaults: { _controller: CoreSphereConsoleBundle:Console:exec, _format: json }
    requirements:
        _method: POST
        _format: json
