console:
    path:  /_console
    defaults: { _controller: CoreSphereConsoleBundle:Console:console }
    methods: [GET]

console_exec:
    path:  /_console/commands.{_format}
    defaults: { _controller: CoreSphereConsoleBundle:Console:exec, _format: json }
    methods: [POST]
    requirements:
        _format: json
