language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install
  - if [[ $TRAVIS_PHP_VERSION = '5.6' && $PREFER_LOWEST = "" ]]; then wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer; fi

script:
  - phpunit
  - if [[ $TRAVIS_PHP_VERSION = '5.6' && $PREFER_LOWEST = "" ]]; then php php-cs-fixer fix . --diff --dry-run -v --level=psr2; fi
